### ISSUE TITLE
Zero Chain EVM compatible

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#101]
## User Story
As engineer I want to deploy smart contracts on ZERO chain so I can use features which are written in solidity.

## Acceptance Criteria

1. check frontier pallet and integrate on ZERO chain 
2. deploy test smart contract interacting with ZERO chain data (eg. ZERO token balance)
3. test the feature

## Additional Information

- to be checked: how to deploy smart contract as external dev?
- block explorer to be EVM compatible  

## How to test

1. a
2. b
3. c
5. d

**Comment by 5-mark** [comment]
duplicate

**Comment by 2075** [comment]
> duplicate
> 
> 

duplicate of which ticket?? pls ref
