### ISSUE TITLE
Wrap up beta feedback findings 

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#107]
## User Story
As product manager focusing on user experience I want the user feedback summarized into actionable tasks so we can build the user interface according to user needs

## Acceptance Criteria

1. analyse https://docs.google.com/spreadsheets/d/1CrAq5Y97rNH5PkjzSj4d5rvFX3fKB6iXTNqjGfl023s/edit#gid=0 beta and discord feedback 
2. consolidate feedback in form of a list 
3. mark actionable tasks and if we already covered them or not

## Additional Information

- prepare ideally for next sync on April 25th 

## How to test

1. see list of consolidated feedback
2. visualise if actionable task is already covered or not

## Link to Notion
https://www.notion.so/zeroio/Beta-feedback-3405a1b072bb4cfbaa0bb939dd286280

**Comment by DarkNebula0** [comment]
@5-mark Current status? Should we create a ticket in notion for this? As far as I can see, this is not a development task.
