### ISSUE TITLE
General Proposal + determine Majority

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#108]
## User Story
As organisation member I want to create a regular proposal so I can let the community vote on my issue.

## Acceptance Criteria

1. Minimum 2 options which the user has to fill (maxlength +/-60 characters)
1.1 The user can add up to 3 more options (to have max 5 options in total) 
2. The voting duration can be configured by setting a start date+time and end date+time
3. The voting algorithm can be selected (see table for information)
3.1 Relative Majority (*the option with the most single votes wins)
3.2 Absolute Majority (*the option with more than 50% of members wins )
3.2.1 the amount of members during proposal creation is the value to compare the absolute majority against
3.2.2 if more then 50% of members vote for one option the proposal period ends earlier.
3.3 Simple Majority (*the option with more than all other options together wins)

## Additional Information

| Algorithm              | Members | Voters | Option 1 | Option 2 | Option 3 | Abstention* | Winning Option  |
|------------------------|---------|--------|----------|----------|----------|-------------|-----------------|
| win relative Majority  | 100     | 60     | 23       | 27       | 10       | 40          | 2               |
| win absolute Majority  | 100     | 60     | 51       | 4        | 5        | 40          | 1               |
| win simple Majority    | 100     | 60     | 31       | 19       | 10       | 40          | 1               |
| fail relative Majority | 100     | 60     | 20       | 20       | 20       | 40          | proposal failed |
| fail absolute Majority | 100     | 60     | 49       | 5        | 6        | 40          | proposal failed |
| fail simple Majority   | 100     | 60     | 23       | 27       | 10       | 40          | proposal failed |

*Abstention is to be considered for absolute majority votings. Absolute majority considers a quorum of more than 50%.

## How to test

1. a
2. b
3. c
9. d

**Comment by 5-mark** [comment]
@vasylenko-yevhen: Good question, we should allow only relative majority for multiple choice votes. Basically it means the option with the most votes will win. 
if we run through multiple choice voting through the different majority scenarios:

 **relative majority**:
-  it would mean one out of many options would need the most votes to win. Would easily work out.
 **absolute majority**:
-  one out of many options would need more than 50% of the **possible votes** to win. Would still work out
**simple majority**: 
-  one out of many options would need more than 50% of all the **submitted votes** to win. Would also still work out. 

If this is causing challenges in the implementation we could start with relative majority for multiple choice voting.


@teejaytotal: please also think this through

**Comment by vovacha** [comment]
@5-mark Absolute majority voting could be finished when we achieved >50% of members. Member's count should be frozen during Voting creation, or should we check it every time the new vote is being processed?
