### ISSUE TITLE
[Create Org] Control Setting

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#110]
## User Story
As organisation creator I want to define who will have control over the treasury so I can set up main organisation rules.

## Acceptance Criteria

1. The second view of the create organisation process visualizes the first step with a checkmark and the second step highlighted while the step 3 remains grey
2. A headline describing the task is available "Who will control the organisation?"
3. 2 radio buttons to select from are visible including text and subtext
3.1 "One entity"
3.1.1 "You have control over the organisation and can decide on treasury spendings" 
3.2. "Community" 
3.2.1 "The community will have control over the organisation and votes on treasury spending proposals"
4. a "Back" button is visible next to the "Next" 
4.1 the "Next" button is only highlighted when a selection was taken

## Additional Information

- Figma: https://www.figma.com/file/8xFCnDl6SlUOonFm1V20ne/GameDAO-Haiku-UI?node-id=230%3A22752
- EPIC: #96 
- since there are no input fields for controller account and treasury account please use the connected wallet address as controller account and use **another static wallet address for the treasury account**.
FYI: the chain currently does not allow the same address for controller and treasury and since the chain misses the feature to create a treasury for the organisation (https://github.com/gamedaoco/gamedao-protocol/issues/21) we will have to move on with a static treasury for all Organisations. 

## How to test

1. dont select anything, click next --> no reaction, no error message
2. select an option, click next --> get to next page
3. click back --> get to first page with last information already filled

**Comment by DarkNebula0** [comment]
Already implemented.
