### ISSUE TITLE
[Create Org] Access Setting

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#111]
## User Story
As organisation creator I want to setup the access rules so I can set conditions on how to become a member of an organisation. 

## Acceptance Criteria

1. The third view of the create organisation process visualizes the first and second step with a checkmark and the third step highlighted
1.1 Three sections are visually separated with a separation bar 
2. first section (access_type) displays a headline and offers 2 options where the second option has two variations
2.1. open  (radio button)
2.2 private (radio button) with a whitelist (checkbox) 
2.3 private with application feature (checkbox)
2.4 private with whitelist and application feature (2 checkboxes)
3. second section offers the 2 options for the fee model (feeModel) 
3.1 no fee 
3.2 fee
3.2.1 selecting fee triggers an input field where the user can enter the fee amount (minimum 1 GAME, max 1 Mio)
3.2.2 if the user enters less than the minimum fee an error message is displayed: "Please enter a minimum fee of 1 GAME"
3.2.3 if the user enters more than the maximum fee an error message is displayed: "Please consider charging a maximum of 1M GAME"
4. the third section captures the member limit
4.1 Headline and subtext
4.2 input field to capture the "memberLimit" prefilled with 0
4.3 if the user leaves 0 the memberLimit will be set to 1 million
4.4. if the user enters a number bigger than 1M we trigger an error message: "Limiting to more than 1M users will be available after you reached 1M users"
5. A back button is available (redirects user to the second step where the provided information are prefilled)
6. a call to action "Save Organisation" is available and inactive as long as the necessary information are not provided or the form contains errors. 
6.1 the call to action saves the Organisation in either the local storage or a centralised or decentralised DB but not on the chain yet
6.2 the user gets redirected to the DAO detail page in preview mode 

## Additional Information

- Figma: https://www.figma.com/file/8xFCnDl6SlUOonFm1V20ne/GameDAO-Haiku-UI?node-id=230%3A23701
EPIC: #96 

## How to test

1. fill all data in all combinations and trigger the error messages
2. get back to step 2 with the back button
3. get to the organisation detail page in preview mode when clicking save organisation

**Comment by DarkNebula0** [comment]
Already implemented.
