### ISSUE TITLE
Setup new chain

### ISSUE THREAD

**Issue by Persqual** [gamedaoco/gamedao-haiku#113]
## User Story
As a developer I want to connect to the new chain to use the new features and index the chain for frontend clients.

## Acceptance Criteria

1. New chain is running ( +SSL )
2. Polkadot.js Explorer can connect

## How to test

1. Go to polkadot js explorer
2. Connect to chain
3. Check if it connects successfully

**Comment by Persqual** [comment]
## User Story
As a developer I want to connect to the new chain to use the new features and index the chain for frontend clients.

## Acceptance Criteria

1. New chain is running ( +SSL )
2. Polkadot.js Explorer can connect

## How to test

1. Go to polkadot js explorer
2. Connect to chain
3. Check if it connects successfully

**Comment by Persqual** [comment]
WSS Provider: wss://beeblebrox.zero.io:9944

**Comment by DarkNebula0** [comment]
Review ✅
