### ISSUE TITLE
Setup Subsquid Archiver

### ISSUE THREAD

**Issue by Persqual** [gamedaoco/gamedao-haiku#114]
## User Story
As a developer I want to bring the chain data into a readable structure so I can use the data in the frontend.
Therefore we need the Subsquid Archiver to run the Subsquid Processor.

## Acceptance Criteria

1. Archiver GraphQL is working
2. Archiver GraphQL delivers extrinsics, events, for the Subsquid Processor

## Additional Information

- GraphQL: https://beeblebrox.zero.io/archiver/console
- This issue is about this section on our diagram:
- https://www.figma.com/file/FNh57oUIJlvKZMkCksplqP/GraphQL-Architecture?node-id=0%3A1:

![image](https://user-images.githubusercontent.com/97976779/166429346-3999af35-8830-4426-b053-c9c5053225f8.png)

## How to test

1. Go to the GraphQL console
2. Try to query extrinsics, events and check the results

**Comment by 5-mark** [comment]
@Persqual how would you get extrinsics from GraphQL? and which events? Is this not more about chain state? 
extrinsics write into the chain. And not sure what we do with events. Could you please clarify?

**Comment by 5-mark** [comment]
@Persqual thanks for clarifying. It is about logging and writing the extrinsics happening on the chain into the archiver. I misunderstood. Now I understand better 🙏🏼
