### ISSUE TITLE
GraphQL index new chain

### ISSUE THREAD

**Issue by Persqual** [gamedaoco/gamedao-haiku#127]
## User Story
As a frontend developer I want to query the chain data. Therefor we need to index the chain for easier access to it's storage.

## Acceptance Criteria

1. Query organizations + members + metadata
2. Query campaigns + contributors + metadata
3. Query identity
4. Query proposals + voters + metadata

## How to test

1. Go to the deployed Subsquid GraphQL version
2. Query different data that is listed on "acceptance criteria"
3. Check if the data is correct

**Comment by Persqual** [comment]
It's done so far except the proposal stuff.
I will finish it in the next days, couldn't do really much this week, because I was sick.

**Comment by 5-mark** [comment]
duplicate and done
