### ISSUE TITLE
[Account] View Collectables

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#145]
## User Story
As user I want to see my collactables so I knwo which items I have

## Acceptance Criteria

1. show user wallets NFTs in a row according to figma
2. click on collectable opens NFT in modal as on https://beta.gamedao.co/app/account (use correct sizes)

## Additional Information

- try reading also other wallets who have more NFTs than just one for testing purposes (eg. check discord faucet for other wallets)

## How to test

1. a
2. b
3. c
4. d

**Comment by 5-mark** [comment]
@hadi-ibra when this will be on haiku?

**Comment by hadi-ibra** [comment]
I configured the right sizes and there is only the display in full screen left, currently I am waiting on confirmation on the theme styles pull request for bug fixes from marco so that when it's merged with the main I could use the styles, so that their won't be conflicts.

**Comment by 5-mark** [comment]
@2075 please clarify the confusion about the colors.
We agreed that figma is the source of truth (since we dont have a web-styleguide). As said I will always check against figma as we do not have any other visual screen. If we want to change colors, so we have to change them in figma first before we add them to the frontend otherwise we will not make progress.

**Comment by hadi-ibra** [comment]
okay great, thank you.
