### ISSUE TITLE
Use alternative to Subsquid GraphQL

### ISSUE THREAD

**Issue by Persqual** [gamedaoco/gamedao-haiku#146]
## User Story
As a developer I want to query, filter, sort, aggregate chain data so I can display it on users.

## Acceptance Criteria

1. Query chain data
2. Filter chain data
3. Sort chain data
4. Aggegrate chain data
5. Subscriptions

## Additional Information

- Try SubGraph
- Try Hasura

## How to test

1. Go to the Hasura GraphQL UI
2. Query data with filters, sorts but also aggregated data
3. Try to subscribe to organizations or campaigns and check if subscription gets triggered

**Comment by 2075** [comment]
Maybe a quick test with SubGraph will also do?

**Comment by 2075** [comment]
what is the current status here?

**Comment by Persqual** [comment]
I'm on it and looking into SubGraph. Will let you updated.

**Comment by Persqual** [comment]
So can we close this or will we keep this issue for Subsquid update with subscriptions?
We're going now with Hasura + Subsquid.
New issue: https://github.com/gamedaoco/gamedao-graph/issues/1
