### ISSUE TITLE
User cannot Leave Wallet Connector

### ISSUE THREAD

**Issue by 2075** [gamedaoco/gamedao-haiku#155]
**Describe the bug**
As user I want to be able to leave any modal overlay situation by either:
- clicking a close button (X)
- clicking somewhere outside the modal
- pressing escape key

_Even reloading the page reinstates the modal overlay!_

**To Reproduce**
1. go to haiku website
2. click connect wallet
3. get stuck in dialogue

**Expected behaviour**
user should be able to exit if he so wishes

**Screenshots**
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/1140449/170935820-5338cfb7-f732-4745-8b08-2a245f49168e.png">

**Comment by DarkNebula0** [comment]
Was actually intended. Either you wanted to use your wallet and used the button or you used an action(transaction) where a wallet is needed.

The modal does not randomly pop up, so you would have to close it.  

But I' m open for feedback and other flows @ux

**Comment by DarkNebula0** [comment]
Is planned in the current sprint
