### ISSUE TITLE
Form validation framework

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#16]
## User Story
As developer I want to integrate a frontend validation framework so I can easily display messages to the user to help him solve his problem.

## Acceptance Criteria

- find suitable next.js / MUI5 compatible and easy to use validation framework
- framework needs to be able to handle i18n (eg. "minimum funding amount is xx$")
- framework needs to be extendable to interpret error codes from the corresponding chain, either directly from the chain, and/or from GraphQL
- error messages need to be maintainable through a i18n translation files also considering variables

## Additional Information

- 

## How to test

1. a
2. b
3. c
4. d

**Comment by soundyogi** [comment]
formik + yup + validators

**Comment by DarkNebula0** [comment]
We now use react-hook-form + yup + i18n.
We decided against formik because it has too many rerender cycles

**Comment by 2075** [comment]
why have the grey tones changed to cold grey again?
