### ISSUE TITLE
Store balances in GraphQL

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#160]
## User Story

- As frontend I want to subscribe to currency balances for an account id based on account `<address>` and optional `<currencyId>` from GraphQL.
- If GraphQL cannot resolve and get balances from the chain, it should return mocked data.

##### Add Balance entity to indexer GraphQL
It should contain the following fields:
| # | name | description |
|--|--|--|
|1| Id | compound id, consisting of account address and currency type |
|2| Identity | reference to Identity hash as `<string>` |
|3| Currency | currency id as `<int>` or enum `<string>` |
|4| Free | free amount of given currency |
|5| Reserved | reserved amount of given currency |

##### Chain events, which are responsible for balances changes are processed by the indexer
1. [Balances](https://github.com/paritytech/substrate/blob/polkadot-v0.9.13/frame/balances/src/lib.rs#L439) events (only applicable to network currency):
   * Endowed - An account was created with some free balance
   * DustLost - An account was removed whose balance was non-zero but below ExistentialDeposit, resulting in an outright loss.
   * Transfer - Transfer succeeded.
   * BalanceSet - A balance was set by root.
   * Reserved - Some balance was reserved (moved from free to reserved).
   * Unreserved - Some balance was unreserved (moved from reserved to free).
   * ReserveRepatriated - Some balance was moved from the reserve of the first account to the second account.
   * Deposit - Some amount was deposited (e.g. for transaction fees).
   * Withdraw - Some amount was withdrawn from the account (e.g. for transaction fees).
   * Slashed - Some amount was removed from the account (e.g. for misbehavior).
6. [ORML currencies](https://github.com/open-web3-stack/open-runtime-module-library/blob/polkadot-v0.9.13/currencies/src/lib.rs#L114) events:
   * Transferred - Currency transfer success.
   * BalanceUpdated - Update balance success.
   * Deposited - Deposit success.
   * Withdrawn - Withdraw success.
 
[Example of such an events](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbeeblebrox.zero.io%2Fnode#/explorer/query/881114).

## How to test

1. Update balances for account via polkadot.js and make sure balance changing events were generated.
2. Wait a while until indexer processes new blocks and events and syncs balance values in its database.
3. See updated values in balance subscription for given account, make sure balances are present and represent actual values from the chain.

**Comment by 5-mark** [comment]
@vasylenko-yevhen isnt this ticket already done?

**Comment by vasylenko-yevhen** [comment]
@5-mark in one of our tech meetings we decided to use different approach to track balance changes, so this feature was done in scope of #216. This one can be closed.
