### ISSUE TITLE
Add ZERO Networks to Network Switch

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#166]
## User Story

As user I want to have a stable enough environment where I can test the product and can rely that my created objects remain there unless announced differently.

## Acceptance Criteria

We have 4 chains running
1. local parachain  --> dev
2. parachain rococo --> stable
3. standalone beeblebrox --> dev
4. standalone alphaville --> stable

------ below this line old content of the ticket "network switch" ------

| ID | Name | Type | Graph | RPC |
|---|---|---|---|---|
| 1 | Development | Devnet Standalone | dev.graph.zero.io | dev.net.zero.io |
| 2 | Staging | Staging Standalone | staging.graph.zero.io | staging.net.zero.io |
| 3 | Development Parachain | Development Parachain | graph.dev.para.sub.zero.io | wss://node.dev.para.sub.zero.io |
| 4 | Staging Parachain | Rococo Parachain | staging.para.graph.zero.io | wss://staging.para.sub.zero.io |
| 5 | Live | Polkadot Parachain | graph.zero.io | net.zero.io |

## Additional Information

- 

## How to test

1. see network switch ( top bar or flyout )
2. select a network
3. content changes according to the selected network

**Comment by DarkNebula0** [comment]
@5-mark The displayed name is shown from the chain, so we need to rename the chain from Development to BEEBLEBROX.

**Comment by 2075** [comment]
also, maybe standalone component which can be placed e.g. in topbar

**Comment by vasylenko-yevhen** [comment]
- Development Parachain: wss://dev.para.sub.zero.io/
- Staging (Rococo) Parachain: wss://staging.para.sub.zero.io/

**Comment by 2075** [comment]
> * Development Parachain: wss://dev.para.sub.zero.io/
> 
>     * Staging (Rococo) Parachain: wss://staging.para.sub.zero.io/

updated the ticket. feel free to use the edit function in the future ❤️
