### ISSUE TITLE
change button name

### ISSUE THREAD

**Issue by 2075** [gamedaoco/gamedao-haiku#167]
Change wording for button so it fits better into the button. 
Use Save for saving the organisation and Create to deploy onchain.

<img width="456" alt="image" src="https://user-images.githubusercontent.com/1140449/173057652-4094bdae-ea62-49f2-ae59-bc7204404c57.png">

**Comment by 5-mark** [comment]
@2075 its not clear what should be done or what is wrong. Please use the bug description template.

**Comment by 5-mark** [comment]
not reproducible
