### ISSUE TITLE
scrollbar error mac dao icons

### ISSUE THREAD

**Issue by 2075** [gamedaoco/gamedao-haiku#168]
fix
overflow x hidden
overflow y tbd
scrollbars result in 

<img width="138" alt="image" src="https://user-images.githubusercontent.com/1140449/173059509-8518f43c-212c-47c2-b083-7b9e99d029d8.png">

should be 

<img width="125" alt="image" src="https://user-images.githubusercontent.com/1140449/173059535-d319a696-bab4-46e9-819f-f94169418051.png">

**Comment by DarkNebula0** [comment]
Scrollbar design for mac and linux needs to be fixed
