### ISSUE TITLE
wallet button disappears

### ISSUE THREAD

**Issue by 2075** [gamedaoco/gamedao-haiku#194]
display of wallet is unreliable, needs to be investigated:
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/1140449/175493982-cc2659f2-55d1-4720-83f1-f1fc6cbce0bd.png">

cannot disconnect or interact with machine.

**Comment by DarkNebula0** [comment]
Happens when the user has not yet added an address to his wallet. @5-mark @ux How should we give the user the information?

**Comment by 5-mark** [comment]
@cargre87 can you try to reproduce and come up with a suitable solution?
thanks

**Comment by 2075** [comment]
> Happens when the user has not yet added an address to his wallet. @5-mark @ux How should we give the user the information?

count the available accounts, if <1 throw/show modal. account selector can turn into 'create account' when count is < 1

**Comment by cargre87** [comment]
The connect button should be stay visible, you need to throw a toast(notification bar) message "Sorry you don't have any accounts on *Walletname" or something simular.
