### ISSUE TITLE
no transactions possible via mobile (eg. nova wallet/polkawallet)

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#221]
**Describe the bug**
Being on a mobile wallet it is not possible to transact as an error appears.

**To Reproduce**
1. open your mobile nova wallet
2. connect to haiku.gamedao.co
3. try joining an organisation

**Expected behavior**
transacting on a mobile wallet on haiku should work as on desktop

**Screenshots**

https://zrag.slack.com/archives/C037HG8UH6Z/p1656413322151359
https://zrag.slack.com/archives/C037HG8UH6Z/p1656413557845439

**Additional context**
also it seems that our wallet connector has a problem

**Comment by 2075** [comment]
the question is, if this is about nova wallet or any mobile wallet. which one do we want to support? is there an agreement eventually which makes sense?
