### ISSUE TITLE
Campaign List Page

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#230]
## User Story
As user I want to browse and explore campaigns so I can find interesting projects on GameDAO.

## Acceptance Criteria

1. Clicking on the "Campaigns" link in the top navi leads the user to the campaigns list page
2. The Title "Campaigns" is on top of the page
3. Some top list elements are available like 
3.1 search bar is which can search in campaign titles and organisation names
3.2 a create campaign button (do not link yet)
3.3 a filter option element
3.4 a sorting element
4. A funding target filter is available with following options (all checkboxes) (refer to "Funding targets table" in additional information)
5. Campaign status filter is available with following (options all checkboxes) (refer to "Campaign status table" in additional information
6. Categories filter with all available categories (all checkboxes)
7. Sorting is possible by (all ascending, descending)
7.1 funding target 
7.2 current funding 
7.3 contributors count  
7.4 alphabetical,
7.5 time left 
8. Campaign Cards are displayed as provided in Figma designs (see additional information)
9. A click on the Campaign Card Image and Title links to the Campaign Detail Page

### **Funding targets table** 
| Funding targets      |
|---------------------|
| < 1,000 $            |
| 1,000 $ - 9,999 $     |
| 10,000 $ - 99,999 $   |
| 100,000 $ - 499,999 $ |
| > 500,000 $          |

### **Campaign status table** 
|   Status   | StatusID |  UI Status  |  Color | Meaning                                                                                                                                   |
|:----------:|:--------:|:-----------:|:------:|-------------------------------------------------------------------------------------------------------------------------------------------|
| Init       | 0        | Not Started | blue   | campaign created but not started yet                                                                                                      |
| Active     | 1        | Active      | yellow | campaign and active. Open for funding.                                                                                                    |
| Paused     | 2        | Paused      | blue   | campaign paused, eg. through GameDAO council vote                                                                                         |
| Finalizing | 3        | Finalizing  | green  | campaign ended, funded and contributions are being processed (eg. from reserved to transfer to DAO treasury)                              |
| Reverting  | 4        | Reverting   | red    | campaign ended, funding goal not reached and contributions are being processed (eg. from reserved to unreserved)                          |
| Success    | 5        | Funded      | green  | campaign ended, funded and contributions are already processed (funds are locked in DAO treasury)                                         |
| Failed     | 6        | Failed      | red    | campaign ended, funding goal not reached and contributions are already processed (all contributions are unreserved / transferrable again) |
| Locked     | 7        | Locked      | red    | campaign locked (eg, through GameDAO council vote)                                                                                        |

Figma: https://www.figma.com/file/8xFCnDl6SlUOonFm1V20ne/GameDAO-Haiku-UI?node-id=616%3A41740

## How to test

1. a
2. b
3. c
9. d

**Comment by 2075** [comment]
suggesting to use similar states with outlined / filled like in proposals @5-mark
