### ISSUE TITLE
Account/ my Balances do not reflect the balances

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#234]
**Describe the bug**
account balances in the account overview are not subscribed to balances, instead its static data.

**To Reproduce**
1. go account overview page
2. click on your wallet
3. compare values of balances 
4. See the difference or also look at the screenshot 

**Expected behavior**
Balances for each currency should be subscribed to graphQL
Also the reserved, transferrable, locked and totals should be visible. 

**Screenshots**
![image](https://user-images.githubusercontent.com/91988132/177384793-8514305c-dc5c-48fd-b847-9c01aec00a46.png)

**Additional context**

query
```
query MyQuery {
  Balance(where: {address: {_eq: "3ZjAeLZWrhu1uFGxgFSPUuSBJmEJZpgHHM6qJUzuHb3B9ykb"}}) {
    id
    reserved
    frozen
    free
    balanceId
  }
}
```

result
```

{
  "data": {
    "Balance": [
      {
        "id": 12,
        "reserved": "0",
        "frozen": "0",
        "free": "0",
        "balanceId": 3
      },
      {
        "id": 11,
        "reserved": "0",
        "frozen": "0",
        "free": "17,000,000,000,000,000,000",
        "balanceId": 2
      },
      {
        "id": 9,
        "reserved": "1,000,000,000,000,000",
        "frozen": "0",
        "free": "99,998,967,936,985,546,861",
        "balanceId": 0
      },
      {
        "id": 10,
        "reserved": "0",
        "frozen": "0",
        "free": "11,999,999,999,999,999,999",
        "balanceId": 1
      }
    ]
  }
}
```

**Comment by 2075** [comment]
requires chain modification. @vovacha @vasylenko-yevhen

**Comment by vasylenko-yevhen** [comment]
Query results are valid and GraphQL correctly reflects balances as they change on the chain.
From the description I can see that GraphQL query results and Frontend output are different.
Also in the attached screenshot account details from the right contain valid valance details, totally matching with the provided query.
I can assume Frontend is using mocked data or different query to fetch the balances.


Also I can see currency ids are static in the balances processing logic but once chain is upgraded to 56 runtime version with new AssetRegistry, graph can fetch currency details (like name, decimals etc) from the chain.

@2075 which chain modifications do you mean?
