### ISSUE TITLE
stablecoin reduced when joining a DAO

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#258]
**Describe the bug**
Joining a DAO reduces the amount of PLAY i have but it shouldnt.

**To Reproduce**
1. top up your wallet
2. go to a DAO and join it
3. compare your balances before and after joining a DAO

**Expected behavior**
only transaction costs should be reduced and if there was a fee it should be reduced in GAME not in PLAY.

**Screenshots**
I had 50 for each asset. the first action I did was joining a DAO but then i had 49.999999x PLAY:
![image](https://user-images.githubusercontent.com/91988132/178501659-69e81bfd-c39a-46e6-ad68-13e4fc1ad043.png)

**Comment by DarkNebula0** [comment]
@5-mark Have you tested it with a new dao? We have changed the currency id. 
Before the id of game was 2. Now Game is 1 and Play is 2

**Comment by 5-mark** [comment]
@DarkNebula0: yes just tested it again with "fundraiser DAO":
![image](https://user-images.githubusercontent.com/91988132/178582508-3efae63a-24fe-42c4-b38f-6c273c90138d.png)

seems like the fee is taken in PLAY token?? Should be GAME.

**Comment by DarkNebula0** [comment]
We have to ask the chain people. As far as I know, the play token is not yet used in the FE.

**Comment by 2075** [comment]
until asset-registry we could simply change the order of GAME and PLAY in the spec? @vovacha

**Comment by vovacha** [comment]
As a temporary solution, I've patched the chainspec on the Beeblebrox node. Later this change will be released and deployed.
