### ISSUE TITLE
Proposals: setting all values correct does not activate the next step button

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#259]
**Describe the bug**
When creating a proposal the form acts weird after selecting a time frame. Next step button gets not activated.

**To Reproduce**
1. Go to the proposals page of your DAO
2. Create Proposal
3. Select date and time
4. See next step button does not get active

**Expected behavior**
when all necessary input fields are filled/selected with valid data the next step button should become active

**Screenshots**
![image](https://user-images.githubusercontent.com/91988132/178502738-e0b6ecdd-cf38-4b41-ae93-ba565658fb54.png)

**Additional context**
Add any other context about the problem here (eg. device/browser)

**Comment by DarkNebula0** [comment]
Try clearing your cache and local storage. 
@5-mark 
![Image](https://user-images.githubusercontent.com/91988910/178503331-c8a6f731-4e4f-419f-8ad4-89cb84610fc8.png)

**Comment by 5-mark** [comment]
@DarkNebula0 how can we ensure, that the regular user does not have to clear his local storage?

**Comment by DarkNebula0** [comment]
@5-mark  We can not. The local storage is currently only an temporary solution.
