### ISSUE TITLE
When creating Proposal the GAME deposit is not considered. 

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#260]
**Describe the bug**
After creating a Proposal and depositing GAME, the GAME is neither locked nor reserved. 

**To Reproduce**
1. Go to your DAO and create a Proposal
2. put some GAME as deposit into your Proposal
3. After creating your Proposal check your balances 
4. See that no GAME was substracted or reserved

**Expected behavior**
When creating a proposal the GAME deposit should be considered. After the proposal is over the user gets back the GAME deposit. 

**Screenshots**
10 GAME was deposited but none GAME was reserved. 
![image](https://user-images.githubusercontent.com/91988132/178503799-afcc933e-4a4d-4671-85b0-6aba8b5900ef.png)

**Additional context**
Add any other context about the problem here (eg. device/browser)

**Comment by DarkNebula0** [comment]
![image](https://user-images.githubusercontent.com/91988910/178525470-c3ea7ba5-6832-43c4-a929-7f607f5962d3.png)

Must first be implemented on the chain. @5-mark @vovacha
