### ISSUE TITLE
Save a “Draft” campaign 

### ISSUE THREAD

**Issue by EDzidziguri** [gamedaoco/gamedao-haiku#269]
### **Statement of Value**

As a Creator
I want to save a "Draft" campaign
So that I will be able to publish it later

———

### **Acceptance Criteria**

1. When a Creator clicks the "Save as draft" button (see Pic.1 (2)) on the first, or second, or third step of the campaign creation flow and the "Campaign title" field is filed in (see Pic.1 (1)), then do the following actions:
• Save the campaign in the local storage
• Open the "Campaigns" tab on the "Organisation" page (see Pic.2)
• Display the saved campaign with the "Draft" tag (see Pic.2 (1))
• Display a notification "Draft has been saved" (see Pic.2 (2))

2. When a Creator clicks the "Save as draft" button (see Pic.1 (2)) on the first, or second, or third step of the campaign creation flow and the "Campaign title" field is empty (see Pic.1 (1)), then display the following error message below the field until one character will be entered - "The Campaign title is required".

3. Draft campaign is not published and is displayed for a Creator only.

4. Draft campaign must be displayed at the bottom of the list below the locked campaigns. The complete order from top to bottom:
• Active campaigns 
• Init campaigns 
• Finalizing campaigns 
• Success campaigns 
• Reverting campaigns 
• Failed campaigns 
• Paused campaigns 
• Locked campaigns
• Draft campaigns 

5. When a Creator clicks the draft campaign card (see Pic.2 (1)), then open the first step of the campaign creation flow (see Pic.1) in the current browser tab and the data saved previously as a draft must be displayed.

———

### **Additional Information**

**Environment**
The functionality specified in this user story must be implemented for the Haiku product - https://haiku.gamedao.co/.

**Design**
• ["Save a draft campaign" flow (desktop)](https://www.figma.com/file/8xFCnDl6SlUOonFm1V20ne/GameDAO-Haiku-UI?node-id=3310%3A86210)

**Images**
<img width="883" alt="Screenshot 2022-07-29 at 21 55 21" src="https://user-images.githubusercontent.com/107074784/181826250-fb121cba-e8fb-438d-8738-e7098068e803.png">
_Pic.1. The "Save as draft" button, "Campaign title" field_

<img width="705" alt="Screenshot 2022-07-29 at 21 58 13" src="https://user-images.githubusercontent.com/107074784/181827001-f6293533-0769-4c47-a51d-1d3bf79be86f.png">
_Pic.2. The "Draft" status, notification_

**Comment by 2075** [comment]
- if it is an offloaded cache, we could use the public key as key and store a json as value, so content can be retrieved again
- if data needs to be private, it could be encrypted with the key
- cache can hydrate the app state when user connects their wallet

**Comment by DarkNebula0** [comment]
There is already a ticket still needs technical refinement
@2075 -> https://github.com/gamedaoco/gamedao-refinement/issues/44
