### ISSUE TITLE
Global Text Editor Component

### ISSUE THREAD

**Issue by PAkhidue** [gamedaoco/gamedao-haiku#276]
## User Story
As a user I want to create a campaign with nice looking content so I can present it better.

## Acceptance Criteria

1. Working Multiline-RTE with text-formatting (bold, italic, links, images... and so on)
2. Drag & Drop Images and upload automatically to IPFS
3. Has to be easy to use for users

## Additional Information

- 

## How to test

1. Write text in RTE
2. Try to format it: bold, italic, underlined
3. Add link to (multiple-)words
4. Drag & drop images
5. Create a table

**Comment by 2075** [comment]
markdown?
