### ISSUE TITLE
Organisation Sorting does not work correct 

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#291]
**Describe the bug**
th sorting on the organisation list page does not work correct, should be fixed.

**To Reproduce**
1. Go to organisation list page https://haiku.gamedao.co/organisations
2. Click on Sorting and select Member:low-high or Member:high-low  
3. See that the sorting does not reflect the amount of members 

**Expected behavior**
Member high-low sorting should sort the organisations descending by member count
Member low-high sorting should show the organisations ascending by member count 

**Screenshots**
![image](https://user-images.githubusercontent.com/91988132/179961543-b398aa4e-11f2-4fca-a6f3-247ca2dffefa.png)

**Comment by developer-sidani** [comment]
### Need to change the displayValues for the organizationSortOptions

### Todo:
- Update the value for each the memberLimit ascending and instead order by:
`{
  "orderBy": {
    "organization_members_aggregate": {
      "count": "desc"
    }
  }
}`
