### ISSUE TITLE
Align frontend with design foundation file 

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#294]
## User Story
As product manager I want the frontend to look as much as possible like the design files in figma so I can guarantee proper product design.

## Acceptance Criteria

1. update colors eg. from violet to cyan and other colors (eg. see screenshots below) 
2. update font colors & weights (eg. see screenshots below) 
3. update border corner radiuses (eg. see screenshots below) 

## Additional Information
Current:
![image](https://user-images.githubusercontent.com/91988132/179963178-a7c8f75f-dc85-4a4c-98b8-4ff1a56be8ba.png)

Figma:
![image](https://user-images.githubusercontent.com/91988132/179962639-8679de65-bcfa-4562-a929-ec085d485e9e.png)

![image](https://user-images.githubusercontent.com/91988132/179967082-e7a763ac-7cf1-496f-84be-2f7afa389d5e.png)

- 

## How to test

1. compare your visuals to figma
2. b
3. c
4. d

**Comment by 2075** [comment]
almost completed...

**Comment by 2075** [comment]
will be replaced by storybook
