### ISSUE TITLE
Setup GraphQL indexer for Zero and Acala

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#30]
## User Story

As frontend developer I want to query all chain information through a graphql api so I can use information into the frontend easily, gain performance and separate frontend from backend. To achieve this the creation of various graphql endpoints is reasonable, to keep building blocks small, maintainable and scalable:

## Acceptance Criteria

1. move all frontend related files into haiku repository
2. "clean up" folder structure 
3. implement graphql endpoints api in nextjs
4. refactor chain queries/subscriptions with graphql queries/subscriptions

## Additional Information

- PR for GraphQL integration: [https://github.com/gamedaoco/gamedao-haiku/pull/24](https://github.com/gamedaoco/gamedao-haiku/pull/24)

## How to test

1. chain information on haiku.gamedao.co are provided by GraphQL queries
2. no chain information left in frontend files which was directly called from the blockchain

**Comment by 5-mark** [comment]
ticket splitted into:
#37 #38 #39

**Comment by DarkNebula0** [comment]
All subtickets are closed
