### ISSUE TITLE
address dropdown with input capability for all places where we need address input

### ISSUE THREAD

**Issue by soundyogi** [gamedaoco/gamedao-haiku#32]
## User Story
As user who interacts with an address form field I want to be able to enter an address and also to select an address from the dropdown fielt so dont make any errors while entering data.

## Acceptance Criteria

1. each wallet address input field shall be an autocomplete-input dropdown
2. when entering a polkadot-chain account address it should be transformed into a local chain address (eg. ZERO)
3. the form field checks if the address is a valid address. 

## Additional Information

- https://mui.com/components/autocomplete/#free-solo
- https://github.com/polkadot-js/common/blob/master/packages/util-crypto/src/address/check.ts

## How to test

1. see dropdown
2. see your addresses inside
3. ability to enter another address
4. polkadot address transforms into a local chain address

**Comment by 5-mark** [comment]
@DarkNebula0 this was already done by you, no?

**Comment by DarkNebula0** [comment]
Yes but not in haiku there are no forms yet

**Comment by DarkNebula0** [comment]
The ticket is old and we already have the component in haiku.
