### ISSUE TITLE
GraphQL Indexer

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#37]
## User Story
As frontend developer I want to query all chain information through a graphql api so I can use information into the frontend easily, gain performance and separate frontend from backend.

## Acceptance Criteria

1. A GraphQL indexer is implemented which can index blockchain data from any Polkadot chain (eg. ZERO, Acala) or other GraphQL indexes and REST apis (eg. Subsquid)
2. chain data should be saved and exposed to own (haiku) GraphQL Server 

## Additional Information

https://github.com/PAIDNetwork/substrate-api-graphql

https://subsquid.io/

https://subquery.network/

## How to test

1. setup subsquid archiver
3. setup subsquid indexer
4. setup postgres db
5. setup subsquid graphql
6. expose endpoints and post a query
7. receive data and nod.

**Comment by 5-mark** [comment]
@Persqual lets further refine this tomorrow morning/middach :-)

**Comment by 5-mark** [comment]
@Persqual please list open todos for this task.

**Comment by Persqual** [comment]
Hey @5-mark these tasks are actually all done. The most is indexed - already exposed and queryable through the interface. Newest is here:

https://app.gc.subsquid.io/beta/test-gamedao-indexer/v005/graphql

You could already test it - only missing thing are now the proposals.

**Comment by 2075** [comment]
- is this already running on the new indexers?
- how about subscriptions?

**Comment by Persqual** [comment]
- Haiku? Nope not yet, I'm on it to add the example on the campaign page and update the org. page with the metadata from GraphQL
- I talked with them on Telegram and they said they have it in their backlogs but with not ETA yet. We could integrate another listener to update this stuff. (Redis, Google Pub/Sub, ...)

**Comment by 5-mark** [comment]
@Persqual if this ticket is done, please update the status. Currently this ticket is in the "in progress" column.

**Comment by Persqual** [comment]
New indexer version with proposals:
https://app.gc.subsquid.io/beta/test-gamedao-indexer/v006/graphql

**Comment by DarkNebula0** [comment]
The ticket is already done and there is a newer one in the current sprint #186
