### ISSUE TITLE
Cannot create Campaign / Content editor not reactive

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#385]
**Describe the bug**
It is not possible to create a campaign, even though everything necessary was filled. 

**To Reproduce**
1. Create campaign in your organisation (you are PRIME)
2. See the new campaign editor
3. upload some pictures, wait 5 minutes, see the picture disappears. 
4. save as draft and re-edit later, see that pictures are not loaded into content editor.
5. Go to final step, fill everything and choose date in the future (start in 10 minutes, end in 2 days)
6. Publish Now Button does not activate 

**Expected behavior**
The glitches in the content editor should be solved. 
Uploaded images should be visible otherwise I am not sure if I already uploaded them.
Publish now button is active when I filled all necessary information, otherwise an error message should be shown about what is missing or wrong. 

**Screenshots**
nope

**Additional context**
in firefox & chrome on beeblebrox tested.
Sometimes all the pictures appear again in the editor.

**Comment by 2075** [comment]
also seems like this bug is back: 
<img width="172" alt="image" src="https://user-images.githubusercontent.com/1140449/189547728-34d0286e-5ee3-42ca-a60d-4cc0be82b7f1.png">

**Comment by PAkhidue** [comment]
We need the caching service to make the images work in the global text editor. 
Creation bug was fixed in #386

**Comment by PAkhidue** [comment]
> Member

Will outsource this issue, I'm not quite sure what causes this.

**Comment by PAkhidue** [comment]
Outsourced the part with the images into #388
