### ISSUE TITLE
IPFS/Image Caching Service

### ISSUE THREAD

**Issue by PAkhidue** [gamedaoco/gamedao-haiku#388]
## User Story
As a developer I want to use IPFS images so I can display them for organizations, campaigns...

## Acceptance Criteria

1. Expose Service API
2. API for Image upload to IPFS
3. API to get image from IPFS/Cache
4. Service has to cache (new) images

## Additional Information

- Advantages would be images that are available immediately after the upload
- It would fix the RTE (Global Text Editor) Image upload problem

## How to test

1. Upload image to IPFS via App(Haiku)
2. Image should be immediately reachable via URL

# possible solutions
- upgrade infura account
- open up to global IPFS network (switch from private --> public)

**Comment by vasylenko-yevhen** [comment]
Response from Infura support:
![image](https://user-images.githubusercontent.com/7493662/194311549-1ff6d6c7-15e2-4453-9eed-19cf50705297.png)

**Comment by PAkhidue** [comment]
Repo & PR in GitLab
