### ISSUE TITLE
Open Graph integration

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#40]
## User Story
As #user I want to see a proper preview image when I share links of gamedao so my post looks nice
## Acceptance Criteria

1. integrate open graph tags for twitter and facebook
2. title: "GameDAO is a community owned cooperative providing fundraising, coordination and ownership protocols for the videogames economy."
3. description: "GameDAO - boot create play trade"
4. image: "https://ipfs.gamedao.co/gateway/QmZxXCMLpqHT9Bz8nsTiZau1tKHeqFvucF9Pp99gYDsfq4"
5. locale: "en_GB"
6. url: current url
7. type: website

## Additional Information

- 

## How to test

1. post a link from gamedao on twitter
2. see proper content on post
3. c
8. d

**Comment by 2075** [comment]
wrong repo. haiku has this already.
