### ISSUE TITLE
Update organization extrinsics

### ISSUE THREAD

**Issue by PAkhidue** [gamedaoco/gamedao-haiku#410]
## User Story
As a user I want to create an organization so I can create my own community.

## Acceptance Criteria

1. Create organization extrinsic throws no error
2. If it fails, display the user a readable & understandable error message
3. If it was successful, organization should be indexed and automatically shown by GraphQL-subscription
4. Join/Leave has to work
5. Update all messages when joining/leaving

## Additional Information

- Extrinsic interface
[extrinsics-v59.txt](https://github.com/gamedaoco/gamedao-haiku/files/9647561/extrinsics-v59.txt)

## How to test

1. Go to the sidebar and press the "+" button to create an organization
2. Try with e.g. no Network-Fees and check error
3. Try with correct data
4. Check if organization was created
5. Check if you're able to join and leave organization

**Comment by 2075** [comment]
@vovacha depends on deployed hasura

**Comment by 2075** [comment]
https://github.com/gamedaoco/gamedao-haiku/pull/422
