### ISSUE TITLE
Mobile Network/Wallet Switcher layout confusing

### ISSUE THREAD

**Issue by PAkhidue** [gamedaoco/gamedao-haiku#416]
Network switch will be hard to reach when we add more items to the wallet switch popup. It's at the bottom of the screen and not scrollable
![NetworkSwitch_Screenshot_2](https://user-images.githubusercontent.com/45153452/192312751-d6128444-5f46-425f-864d-45df1de0baa7.png)

I think the wallet switcher is confusing in mobile view - avatar confuses at the top of the screen:
![image](https://user-images.githubusercontent.com/45153452/192324215-7f7a4f7c-1da6-4eb4-9e6d-e750174d6919.png)

**Comment by 2075** [comment]
- hide network switcher

**Comment by PAkhidue** [comment]
already done in #427
