### ISSUE TITLE
async

### ISSUE THREAD

**Issue by 2075** [gamedaoco/gamedao-haiku#42]
https://github.com/gamedaoco/gamedao-haiku/blob/ffc9cf88a452f318c169e11ba0a799ab89794d66/pkg/app/src/pages/_document.tsx#L63

Better non blocking?
```<script async type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js" />```

**Comment by DarkNebula0** [comment]
@2075  I can't tell you why but when I try to load it as an npm package the next js window error comes up again

**Comment by 2075** [comment]
will check

**Comment by DarkNebula0** [comment]
@2075 Did you find out anything or is the ticket outdated?
