### ISSUE TITLE
state hydration / caching not working

### ISSUE THREAD

**Issue by 2075** [gamedaoco/gamedao-haiku#429]
## Problem
when loading a view, eg account flyout, everytime the data is pulled from the graph therefore you always see the loader even if you just loaded the data.

## Solution
caching and proper state hydration should fix this.

[ ] write https://www.apollographql.com/docs/react/caching/advanced-topics/
[ ] test the outcome

**Comment by 2075** [comment]
assigned @andre to have a look when all is completed

**Comment by 2075** [comment]
write caching policy for graphql subscriptions #435

**Comment by andre** [comment]
> assigned @andre to have a look when all is completed

You've got the wrong Andre :)
