### ISSUE TITLE
Wallet Connect

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#44]
## User Story
As user I want to connect my wallet with gamedao so I can interact with the app

## Acceptance Criteria

1. The connect button contains "connect wallet"
2. Clicking the button leads to a modal:
2.1. If no polkadot.js or talisman wallet is installed the modal title says "No wallet found" and a list of wallets appear which can be installed (see Screenshot 1)
2.2. The listed wallets link to the corresponding pages (see links in Additional Information)
3. If at least one wallet is installed the same modal appears with the title "Select wallet" (see Screenshot 2)
3.1. The installed wallets are linking to connect the wallet
3.2 The not installed wallets are linking to the corresponding wallets (see links in Additional information)  
4. external links always open in a new tab
5. when the users wallet is connected the modal closes and the connect button is replaced by the wallet component

## Additional Information

Screenshots are to be understood as example and not as final designs

Screenshot 1:
![image](https://user-images.githubusercontent.com/91988132/158891271-0faa8067-2662-4389-a0df-1b3c3aa86bc5.png)

Screenshot 2:
![image](https://user-images.githubusercontent.com/91988132/158894022-9dcd9678-366f-4019-82ae-a482e42612ae.png)

Screenshot 3 (when both wallets installed):
![image](https://user-images.githubusercontent.com/91988132/158893906-f5ed9f77-5994-4a43-a4be-12b9184be0a7.png)

Screenshot 4 (illustration how iconography could look like):
![image](https://user-images.githubusercontent.com/91988132/158894414-65f63a09-9e70-4afc-95ff-e8a7b33f1168.png)

### Wallet Links
Link Polkadot.js wallet: https://polkadot.js.org/extension/
Link Talisman wallet: https://talisman.xyz/
We do not link directly to the corresponding extension store of the browser, so that we dont have to update links if they change in the future.

###Process View
![image](https://user-images.githubusercontent.com/91988132/158896734-5184b357-83e1-4dea-8c30-d39d29193fb5.png)

## How to test

1. have no wallet installed (eg. inkognito tab) and click connect button 
2. run through 2.1 & 2.2
3. have polkadot.js installed 
4. run through 3, 3.1, 3.2
5. check all links (also if the open in new tab)
6. when connected see modal closing and wallet component 

## Link to UI in Figma 
https://www.figma.com/file/8xFCnDl6SlUOonFm1V20ne/?node-id=3%3A15

**Comment by 5-mark** [comment]
@teejaytotal please review this ticket and prepare corresponding components for it with Figma screen design. 
Please give feedback if you see more or changes to the ticket.  
Please update accordingly with the right links to Figma

**Comment by 5-mark** [comment]
@teejaytotal Please update ticket with necessary Figma Links and discuss with frontend team upfront, if necessary.
Target should be to get this ticket into the sprintlog.

**Comment by teejaytotal** [comment]
@5-mark  updated
