### ISSUE TITLE
Cannot join organisation

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#455]
**Describe the bug**
When trying to join an organisation an error is shown "Join Organisation failed"

**To Reproduce**
1. Go to an organisation which accepts members
2. Have enough token ZERO/GAME
3. Click join organisation 
4. See error message and console log or screenshot

**Expected behavior**
Join organisation should work and if not a reason why it failed should be shown. 

**Screenshots**
![image](https://user-images.githubusercontent.com/91988132/195440891-a5d622e8-c934-4a83-a4e1-a33f744be0e1.png)

**Additional context**
when using polkadot.js app extrinsic "bad origin" is shown as response

**Comment by vovacha** [comment]
I believe this should be fixed with the latest chain version, which is already deployed to stage env.
Fix: https://github.com/gamedaoco/gamedao-protocol/pull/109

Dev env will be updated today with a new chain and graph.

**Comment by 2075** [comment]
how can stage be updated before dev? :)

**Comment by 5-mark** [comment]
fixed
