### ISSUE TITLE
cannot create community DAO

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#463]
**Describe the bug**
When creating a community governed DAO i  receive an error. 

**To Reproduce**
1. Create organisation
2. Choose Community 
3. submit extrinsic

**Expected behavior**
Community governed DAO should be possible
The error message should state what went wrong. 
**Screenshots**
![image](https://user-images.githubusercontent.com/91988132/198000916-dd01ec14-fdf8-4c29-be1b-0b1d4f604ed4.png)

**Additional context**

**Comment by 2075** [comment]
- on which branch / version did this happen, this looks old

**Comment by 5-mark** [comment]
happened on dev via frontend, However I can submit a DAO governed organisation through polkadot.js apps extrinsic. Therefore my guess would be a wrong parameter is sent to the backend. 
@2075 @AlexisZero

**Comment by AlexisZero** [comment]
on all of them, we were trying to create "company" instead of "DAO" when selecting a community organization.
