### ISSUE TITLE
Cannot join organization

### ISSUE THREAD

**Issue by EDzidziguri** [gamedaoco/gamedao-haiku#484]
**Bug:**
I cannot join organization with a connected wallet and a sufficient balance.

**Steps to reproduce:**
1. Open https://stage.gamedao.co or https://dev.gamedao.co
2. Click "Guilds" section in the header
3. Click an organization.
4. Click the "Join organization" button.
5. Click the "Submit" button.
6. Sign translaction in Polkadot JS extension.

**Expected result:**
A user joins an organization.

**Actual result:**
The following error is displayed:

![Image](https://user-images.githubusercontent.com/107074784/201597669-9bdd152c-fac8-4470-8904-c9c975da3a4c.png)

![Image](https://user-images.githubusercontent.com/107074784/201597711-090fc167-d9ca-4b4f-b5dc-827d207609e2.png)

**Comment by 2075** [comment]
inability to pay some fees -> not enough monies in your stash

**Comment by EDzidziguri** [comment]
> inability to pay some fees -> not enough monies in your stash. either old data in local storage or wallet not fulled enough. on disco faucet you can get more tokens like this: '!loot dev|stage walletadr'

The problem is that I've requested money twice and I have sufficient balance. I also created cache a few times.

**Comment by 2075** [comment]
@EDzidziguri 
- dev faucet: `!loot dev <address>`
- staging faucet: `!loot stage <address>`

**Comment by EDzidziguri** [comment]
Checked again on stage env and it works. I'm closing the bug.
