### ISSUE TITLE
Cannot create organization

### ISSUE THREAD

**Issue by EDzidziguri** [gamedaoco/gamedao-haiku#485]
**Bug:**
I cannot create organization with a connected wallet and a sufficient balance.

**Steps to reproduce:**
1. Open https://stage.gamedao.co/ or https://dev.gamedao.co/
2. Click the "+" button in the sidebar.
3. Fill in all required fields.
4. Click the "Save organization" button.

**Expected result:**
The "Save on Chain" button is enabled.

**Actual result:**
The "Save on Chain" button is disabled:

![Image](https://user-images.githubusercontent.com/107074784/201598564-a0fbebd2-03d0-47d2-a40f-8bc67d0045c3.png)

**Comment by 2075** [comment]
please show balances and empty apö storage before testing again

**Comment by EDzidziguri** [comment]
This issue is sorted out. The problem was in images that haven't been uploaded, but they are mandatory.
