### ISSUE TITLE
UX-Glitches-Complete-List

### ISSUE THREAD

**Issue by cargre87** [gamedaoco/gamedao-haiku#493]
*Describe the bug**
UX-Glitches a complete List - can be filled more in the Future

**To Reproduce**

1 - when creating a DAO the transaction modal does not show the GAME deposit value. It was there before and now gone. 
2 - for all tables use MUI Data Grid Style and style (backdrop,hover) it like shown in Figma (Screenshot below or link below)
3 - Account Overview - My Campaigns - Campaign Contributions - Not hoverable and not clickable
4 - Organisation Overview - Header with Banner & Avatar - Area where the Tabs-Menu sits is to high
5 - Overhal all Skeletons based on the rendering informations - Don't render all and sort then
6 - for inputs that needs a value >1 (like Deposit on DAO Creation) allow user to delete all input, if input <1 than show the box yellow and throw a inline error with " Value can't be <1" 

***
7 - Datepicker - Actual Component not suitable - FIX SOON

**Expected behavior**
1 - show DAO GAME deposit value
2 - like described below
3 -Account Overview - My Campaigns - Campaign Contributions -  make it hoverable and clickable to the actual campaigns
4 - Organisation Overview - Header with Banner & Avatar - make it same height like shown in figma 
5 - like described below
6 - like described below

***
7 - SOON

**Screenshots**

1. Misses on GAME Deposit
![Bildschirmfoto 2022-08-31 um 17 29 04](https://user-images.githubusercontent.com/110457238/187718051-9bae1996-22f5-4e8a-92e6-115a3dd9b868.png)

2. Table Header Backdrop 
![Bildschirmfoto 2022-08-31 um 17 33 44](https://user-images.githubusercontent.com/110457238/187719102-3e7a2717-df65-4c32-b251-8c2cbc3229be.png)

3. No hover no clicky 
![Bildschirmfoto 2022-08-31 um 17 37 16](https://user-images.githubusercontent.com/110457238/187719901-67206e9d-a937-41b8-805f-983e35363534.png)

4. Live (Production) 
![Bildschirmfoto 2022-08-31 um 17 37 59](https://user-images.githubusercontent.com/110457238/187720116-c1c5ce41-45a6-4a6a-a6ee-2d9b5099c425.png)

4.1 Figma (UX) 
![Bildschirmfoto 2022-08-31 um 17 38 14](https://user-images.githubusercontent.com/110457238/187720192-0c6e7d93-b498-4893-b75c-499e56fcb7ff.png)

5. Live (Production) 
![Bildschirmfoto 2022-08-31 um 17 40 19](https://user-images.githubusercontent.com/110457238/187720593-9a70f3ed-7ffd-4f9a-8fa7-1d0acc652b65.png)

6. Live (Production) 
![Bildschirmfoto 2022-08-31 um 17 41 26](https://user-images.githubusercontent.com/110457238/187721092-40e6dbf9-5b29-4193-9d15-ea720692184a.png)

***
7. SOON

**Additional context**
FIGMA FILE OF UNSPOKEN TRUTH : [https://www.figma.com/file/8xFCnDl6SlUOonFm1V20ne/GameDAO-Haiku-UI?node-id=0%3A1](url)

**Comment by 2075** [comment]
- thanks, good job

- i think we should focus in a first step to fix  >>> functionality <<<
- i think we should focus in a first step to fix  >>> functionality <<<
- i think we should focus in a first step to fix  >>> functionality <<<

- design glitches should be fixed during storybook migration if too complicated

- many things already changed due to refactoring... be prepared 🗡️

**Comment by AlexisZero** [comment]
First point is already fixed 
![Screenshot from 2022-11-18 14-57-16](https://user-images.githubusercontent.com/114652006/202721603-890e32c5-c1e3-4d67-9cac-bdf6818dc530.png)

**Comment by AlexisZero** [comment]
Second point no longer applies due to the glass design overhaul.

**Comment by AlexisZero** [comment]
4th point is also fixed, the height is now adjusted and ok

**Comment by AlexisZero** [comment]
I will look into input validations, for the 6th one. Right now we are using that behaviour as validation, it should be changed to what carsten suggested.

**Comment by AlexisZero** [comment]
I will see if I can fix the 5th one
