### ISSUE TITLE
Join Guild by logging into Discord (BE)

### ISSUE THREAD

**Issue by EDzidziguri** [gamedaoco/gamedao-haiku#496]
### **Statement of Value**

As a user
I want to join a guild by logging into my Discord account
So that I will be able to buy a battlepass

———

### **Acceptance Criteria**

1. An anonymous user must be able to join a guild in the following way:
1.1. A user clicks the "Join Guild" button on UI.
1.2. Redirect a user to the Discord authenticate page in a current browser tab.
1.3. After a user loggs in on the Discord authenticate page do the following actions:
• Redirect a user back to the Guild page
• Make him a member of the "Wave" guild
• Save his account with the following parameters in a DB (not on chain):
`Internal user ID`
`Discord ID`
`Discord username` (a Discord username will be displayed on UI after a user logs in)
`XP points` (a user will get XP points for connecting his Discord account)
`Discord Avatar` (a Discord avatar will be displayed on UI after a user logs in)

2. A user must be able to log in with Discord in the following way:
2.1. A user clicks the "Log in with Discord" button on UI in the header.
2.2. Redirect a user to the Discord authenticate page in a current browser tab.
2.3. After a user loggs in on the Discord authenticate page do the following actions:
• Redirect a user back to the page from which he clicked the "Log in with Discord" button in the header.
• Save his account with the following parameters in a DB (not on chain):
`Internal user ID`
`Discord ID`
`Discord username` (a Discord username will be displayed on UI after a user logs in)
`XP points` (a user will get XP points for connecting his Discord account)
`Discord Avatar` (a Discord avatar will be displayed on UI after a user logs in)

3. A user should be able to join a guild after logging in with Discord in the following way:
3.1. After a user clicks the "Join Guild" button on UI, do the following actions:
• Make him a member of the "Wave" guild in a DB (not on chain) if the wallet is not connected or make him a member of the "Wave" guild on chain if the wallet is connected

4. A DB must allow to manage user accounts (CRUD).

5. A user might connect his Twitter account before connecting a wallet. Thus, it should be possible to save `Twitter ID`.

6. A user must be able to leave the guild. In this case there's no need to save his activities related to the guild he left. 

———

### **Additional Information**
[Join Guild user flow](https://www.figma.com/file/qQo4HA3HT9yUv9RVZ6kHec/User-Journey-Map-for-Guild-Squad?node-id=908%3A12320&t=Iu77PPjwAIcnMp8I-4)

[Log into Discord user flow](https://www.figma.com/file/qQo4HA3HT9yUv9RVZ6kHec/User-Journey-Map-for-Guild-Squad?node-id=908%3A12321&t=Iu77PPjwAIcnMp8I-4)

**Comment by 2075** [comment]
how would the flow differ looking from the perpective of a discord user on discord joining, from the web site flow?
