### ISSUE TITLE
Reorder Layout

### ISSUE THREAD

**Issue by 2075** [gamedaoco/gamedao-haiku#61]
**Describe the bug**
Layout all over the place

**To Reproduce**
1. Go to internetz

**Expected behavior**
- footer should render below sidebar and content area
- sidebar should have min height 100vh-topbar height

**Screenshots**
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/1140449/160706931-bb3da5a8-207e-4256-b2c0-f3a8a3f362ba.png">

@5-mark

**Comment by DarkNebula0** [comment]
"footer should render below sidebar and content area."

Would not work efficiently 
Currently a mui drawer is used the position fixed. for the mobile view. Either we need to render different components for the sidebar or calculate all the elements around it


Before I tackle the layout again we need the new navigation concept and designs from ux team @5-mark @mikeplanzer.

**Comment by 2075** [comment]
should work as designed.
