### ISSUE TITLE
Network Connection should be non blocking for landing page

### ISSUE THREAD

**Issue by 2075** [gamedaoco/gamedao-haiku#62]
## User Story
As #user I want to see the page quickly so I can use it.

## Acceptance Criteria

1. go to page
2. no waiting until landingpage is shown

## How to test

1. go to page
2. landingpage shows quickly

<img width="485" alt="image" src="https://user-images.githubusercontent.com/1140449/160707506-63d512a0-9347-44ba-a9cf-80cfbb496f29.png">

**Comment by DarkNebula0** [comment]
The spinner is only displayed until config and feature are loaded from GraphQL.
Since they determine how the page looks, it would come to strange loading behavior.
We should rather look how to get the loading time shorter / more efficient

**Comment by 2075** [comment]
config and features are provided through graphql but data is coming directly from the api, therefore if it is only this data, the loading and parsing should jsut be a question of ms.

the loading time seems to be long because of something else, e.g. if the network connection is established at the same time vs immediately after getting config and features?

**Comment by DarkNebula0** [comment]
The question is, does vercel need a long time in the background until the GraphQL is ready, or does the frondend need a long time until it executes the request?

https://github.com/gamedaoco/gamedao-haiku/blob/245fede0c0e91dff7634ee69c0a67c111f22f8bf/pkg/app/src/provider/ready/readyProvider.tsx#L12

**Comment by DarkNebula0** [comment]
On localhost it takes only ms.

**Comment by 2075** [comment]
what i see is: 
- blockchain connections come first
- could be related to warm up times for the api route
- also initial render kinda slow and big files
<img width="641" alt="image" src="https://user-images.githubusercontent.com/1140449/160804791-3207bd16-476e-4766-b913-e1cdd3017d75.png">

can you see this: https://profiler.firefox.com/from-browser/calltree/?globalTrackOrder=x50wx4&hiddenGlobalTracks=1w35w79wx4&hiddenLocalTracksByPid=83671-1w8~88704-0~58941-0~58968-0~59082-0~83694-0w2~83680-0w4&implementation=js&localTrackOrderByPid=83671-90w8~59070-0~88704-0~58941-0~58968-0~59082-0~83694-0w2~83680-0w4&thread=d&timelineType=cpu-category&v=6

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/1140449/160805161-560aaab0-ec34-49f0-bd3b-5a60e499a30a.png">

**Comment by 2075** [comment]
i am getting up to 11s

**Comment by DarkNebula0** [comment]
Your profiler links do not work properly or cut off important information. Can you create a har file for me. 

What I see with my browser are 2-5s and that is reflected with the verscel log of the function time.

![image](https://user-images.githubusercontent.com/91988910/160807017-34a5251c-461e-459c-b6c8-a02f1b392057.png)

![image](https://user-images.githubusercontent.com/91988910/160807677-b5ed2350-4208-4eb6-be9e-5856fa56dbcc.png)

**Comment by 2075** [comment]
- use the second link
- slow. lets work on the cold start, will also look into it

**Comment by 2075** [comment]
what we did in the past with lambdas was to have a ping service sending requests often so the lambda does not cool down.
could be an alive endpoint. maybe connecting a logger to that could also help.

**Comment by DarkNebula0** [comment]
Just saw that there is also an open issue on this topic at vercel. 
Seems to be due to graphql and apollo. The query of the rmrk schema could also be related to this.

https://github.com/vercel/vercel/issues/6292

**Comment by 2075** [comment]
ah, the oldest problem of serverless. lets try keeping the lambda warm then for now.

**Comment by 2075** [comment]
following up on this, maybe we should keep config and features in the local storage and let the app start, when data arrives we diff the config and features and app gets updated. @5-mark @DarkNebula0

**Comment by DarkNebula0** [comment]
Was fixed with the GraphQL move to aws.
