### ISSUE TITLE
[NAV] Top Navigation

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#69]
## User Story
As GameDAO user I want to see most interesting links on the top navigation so I can access them from anywhere of the page easily.

## Acceptance Criteria

**Mobile**
1.  Shows top bar navigation which is sticky on scroll
1.1 On the left there are 3 dots which open the organisations sidebar [#70]
1.2 In the middle the logo is shown
1.3 The logo is linked to the app root url
1.4 On the right the wallet and burger navigation are shown
2. Wallet [#78]
2.1 When not connected there is a button shown
2.2 When connected the button turns into an avatar
2.3 Clicking on the avatar opens a the wallet flyout [#78]
3. Burger Navigation
3.1  Clicking on burger navigation opens side-panel from right to left
3.2. Navigation items are listed as follows
3.2.1. Link Organisations List Page with "Organisations" to "/app/organisations"
3.2.2. Link Campaigns List Page with "Campaigns" to "/app/campaigns"
3.3.3. Link "Quests" to "/app/quests"
3.3. At the bottom a helper text + button to the documentation is shown
3.4. Social media icons are shown at the very bottom linking to the corresponding plattforms

4. _Search bar not to be included yet_

## Additional Information

- part of EPIC: #68 

UI Mockups: https://www.figma.com/file/8xFCnDl6SlUOonFm1V20ne/?node-id=3%3A17
Design System: https://www.figma.com/file/5L4VE8EIhRVB6kfIB50zlT/Minimal-Web?node-id=1489%3A112412 

## How to test

1. a
2. b
3. c
12. d

**Comment by mikeplanzer** [comment]
Acceptance criteria added, please review @5-mark
