### ISSUE TITLE
[NAV] Organisation Sidebar

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#70]
## User Story

As user I want to see organisations which i am a member of, so I can easily select and switch between organisations

## Acceptance Criteria

1. A quick access bar listing organisations is in place (for all viewports)
1.1. all organisations the user is a any type of member / owner of are listed
1.2. the organisations are sorted alphabetical
1.3. **Desktop**: The sidebar is always visible. Fixed on the left side of the browser window
1.4. **Mobile**: The side bar is shown by clicking on the 3 dots sitting within the header component
1.4.1. When the sidebar is present, the page content is moved to the right by the width of the sidebar

2. clicking/tapping on one of the organisation logos highlights the clicked organisation and opens the organisation overview page
2.1. When organisation is selected the position of the avatar remains at the original position

3. The sidebare comes in following states:
3.1 No DAO: This is used when the connected wallet is no member / owner of any organisation. In this case the sidebar shows a plus circle which links to the dao creation page
3.1.1. if the user is not connected, a modal which can be closed appears and displays "Please connect your wallet."
3.2. DAOs listed: If one or more DAOs are listed they are shown at the beginning of the list followed by a separator line and the dao creation circle button
3.3. DAO with update: If a DAO has a notification (example new proposal) a small circle is shown on top of the DAO avatar (if the user has seen the news, the notification is gone)
3.4. Many DAOs: If the sidebar lists more organisations than there is available space, I can scroll vertically with the mouse or swipe with the finger through these organisations. The last item in the list is cut off and a gradient overlay is on top of the avatar to indicate the scroll
4. The sidebar is sticky and the footer will be right from the sidebar for both viewports

## Additional Information

- The Design in Figma are shown in desktop and mobile view and are _customized_ components.

UI Mockups: UI Mockups: https://www.figma.com/file/8xFCnDl6SlUOonFm1V20ne/?node-id=3%3A17
Design system: https://www.figma.com/file/5L4VE8EIhRVB6kfIB50zlT/Minimal-Web?node-id=1489%3A112412
- part of EPIC: #68 

## Interaction Example Mobile

https://user-images.githubusercontent.com/25332596/161392681-53e23072-58b1-41c5-b30c-a4192c5b5012.mov

## How to test

1. be not loggedin and interact with the side bar (click the + and receive modal with the message to connect your wallet) on mobile and desktop
2. be loggedin and no member of a DAO, click the + and get to the create organisation form on mobile and desktop
3. be loggedin an member of one DAO, click the DAO and see page content changing to the dao detail page and the url is updated
4. be loggedin and member of several DAOs, resize your screen and scroll the DAOs make sure everything looks like in the design on mobile and desktop, click on a DAO an make sure that the page content and url is updated

**Comment by 2075** [comment]
will be hard to sort by most recent activity, would recommend alphabetical or user defined.

**Comment by mikeplanzer** [comment]
Acceptance criteria updated + added interaction example for the mobile view.
Also added the alphabetical order @2075
