### ISSUE TITLE
[ODP] Organization context navigation — draft

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#71]
## User Story
As a DAO member I want to navigate though relevant pages in context of the respective DAO. 

## Acceptance Criteria

1. the context navigation is below the main teaser on mobile and desktop
2. Following links are available in the org navigation:
- Overview (links to Organisation Dashboard)
- Proposals (links to proposal page listing org-related proposals)
- Campaigns (links to a campaign overview page listing org-related campaigns)
- Treasury (links to a treasury overview page listing organisation assets) 
- Members (links to members page listing member accounts indicating identities)
- Settings (links to the org-related settings page)
3. each subpage loads when clicking the nav point

## How to test

1. a
2. b
4. c
5. d

**Comment by DarkNebula0** [comment]
The ticket is outdated.
