### ISSUE TITLE
[ORG] Filtering of organizations

### ISSUE THREAD

**Issue by mikeplanzer** [gamedaoco/gamedao-haiku#84]
## User Story
As user I want to filter the organisations so i can narrow down organisations I am looking for.

## Acceptance Criteria

1. A filtering option is placed on the top of the organizations list page
2. Per default no filter option is selected
3. Clicking on the filter option triggers a slide-out from the right showing the filter options
3.1 The slideout shows the title "Filters" followed by a close icon
3.2 Filter options are liste below each other
3.3 At the bottom of the slide-out panel a "clear" button is present
4. Following filter options are available 
4.1. By organisation type: (Individual, Company, DAO, Hybrid) --> all checkboxes // _see additional infomation_
4.2. By member access: (open, private) --> radio buttons
4.3. By fee model (fee, no fee) --> radio buttons
5. filter takes also search term into consideration
6. The filter component can be deactivated / activated ... @5-mark 

## Design
https://www.figma.com/file/8xFCnDl6SlUOonFm1V20ne/?node-id=3%3A18

## Additional Information
Organisation Type Rules:
Individual = treasury owner is prime
Company = treasury owner is prime + KYB done
DAO = treasury owner is community 
Hybrid = treasury owner is community + KYB done

part of EPIC: [#86]

## How to test

1. a
2. b
3. c
7. d

**Comment by DarkNebula0** [comment]
@5-mark What is the status of the issue?

As I see the filter works on the current page so we could close this and #86
