### ISSUE TITLE
GraphQL to handle different chain versions, structs and types

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#88]
## User Story
As gameDAO manager I want to ensure that the frontend can consume data from different chains and chain versions so that I can rely on a resilient and operational platform.

## Acceptance Criteria

1. GraphQL handles types from different chain versions (eg. zero old version and new version with pallets based on substrate V3) 

## Additional Information
- consider GraphQL update
- consider Frontend update 
- try to autogenerate as much as possible
- @Persqual, @vasylenko-yevhen, @2075 could you refine the ticket better so we get a read-2-develop ticket?

## How to test

1. a
2. b
3. c
4. d

**Comment by vasylenko-yevhen** [comment]
_Technical:_
It was not clear, which value Subsquid uses to determine extrinsics version changes.
Developer on the Subsquid seminar [claimed](https://youtu.be/CVK77w18z2g?t=1261) that the value might me block hash, which introduces runtime changes.
But based on [this source code](https://github.com/subsquid/squid/blob/master/substrate-metadata/src/events-and-calls.ts#L48-L59), it is clear hash is constructed based on the extrinsic metadata, like parameter types/names. So it's generic enough to work on multiple environments of the same chain (like alphaville/beeblebrox) without extra efforts to manipulate with those hashes.
```ts
private computeHash(name: QualifiedName): string {
  let def = this.get(name)
  let fields = def.fields.map(f => {
      return {
          name: f.name,
          type: getTypeHash(this.types, f.type)
      }
  })
  return sha256({
      fields
  })
}
```

**Comment by vasylenko-yevhen** [comment]
As there are components of the project, which are relaying and depending on the chain, it's needed to account for those parts during delivery process.
I would like to suggest few rules to be accounted for during Chain/Graph/Frontend integration.

1. Create new chain versions few days before deploying it to alphaville/beeblebrox.
2. Use tags to make chain versions fixed. Graph and frontend would rely on those tags instead of branches/commits.
3. Communicate to team about changes, introduced in new chain version. 
4. Implement according changes on the Graph and Frontend parts.
5. Perform chain upgrade once all of the changes supported by every component.

**Comment by 5-mark** [comment]
@PAkhidue / @vasylenko-yevhen whats the status of this ticket? who has the next task to do?

**Comment by vasylenko-yevhen** [comment]
@5-mark further step is to deploy all related GraphQL items to the standalone parachain, using docker-compose which already includes all required services. Once that done and tested, we can use compose stack for any other environment.

**Comment by 2075** [comment]
when will the parachain + graphql stack be operational? waiting already since two sprints. would be great to get a feeling for that! :) @PAkhidue @vasylenko-yevhen ⏲️

**Comment by PAkhidue** [comment]
> when will the parachain + graphql stack be operational? waiting already since two sprints. would be great to get a feeling for that! :) @PAkhidue @vasylenko-yevhen ⏲️

Hey, we're currently on it, I think the set up will be ready today/tomorrow evening.
I will create a repository with all the docker-compose files to set up the GraphQL.

Afterwards I really want to update the Squid to FireSquid and also want to have a look with the different version handling.
Already have an idea how to deal with it, so I try to do it while upgrading the whole app.

**Comment by PAkhidue** [comment]
It looks like the starting point of the earlierst version is v58 (chain). We should handle all versions from there on. Update Graph-Ticket is #382.
