### ISSUE TITLE
Setup Configuration Framework for Feature Toggles

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#92]
## User Story
As gamedao platform managerI want activate/deactivate features and components without deploying the backend so I can react on external factors.

## Acceptance Criteria

1. frontend components shall be enableable (eg. search bar)
2. frontend features  shall be enableable (payment with ramp)
3. chain features shall be shall be enableable (eg. governance protocol, create organisation)
4. when a configuration is activated no backend deployment is necessary

## Additional Information

- 

## How to test

1. de-/activate a frontend component and see them in-/active in the frontend 
2. de-/activate a frontend feature and see them in-/active in the frontend 
3. de-/activate protocoll features onchain and see them in-/active in the frontend

**Comment by 5-mark** [comment]
@5-mark provide prioiritised list for chain feature enablement

**Comment by DarkNebula0** [comment]
@5-mark  Is implemented in the frontend maybe we should create a ticket in the Protocol repo for the chain.
