### ISSUE TITLE
[UX] Account 

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#94]
## User Story
As user I want to view my account so I can inform myself and take care about my account related data.

## Acceptance Criteria

1. view my network wallet balances in detail (transferrable, locked, reserved etc)
2. view & claim onchain identity
3. view & claim KYC (no objective for AA cycle, do ideation about visualising KYC status, keep static)
4. view achievements (no objective for AA cycle, do ideation about visualising achievements, keep static) 
5. view collectibles (including information about the collectible)
6. view participations (eg. funded campaigns etc.)
7. view update log (do ideation about: notifications, starting/ending campaigns, rewards to be claimed etc.)
8. view transaction log (all transactions made on GameDAO including descriptive information) 

## Additional Information

- please add more topics if you see more or reassign topics which you think are not related to account
- all points do not represent account menu items, maybe some of the points can be merged behind one menu item.

## Links to wireframes:

Link to figma with wireframes and navigation proposal 
- anchor links to stay on page & full page for settings 
- descriptions can be found on file
https://www.figma.com/file/NQ2MpTJlQ1fwWhSZ5hsHCx/Wireframe-%26-Sketches?node-id=135%3A16872

- added _proposals_ to the dashboard
please review @5-mark @mikeplanzer 
andre

**Comment by 2075** [comment]
are all the AC met?
