### ISSUE TITLE
Voting within Organisation

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#95]
## User Story
As organisation member I want to create proposals and participate in voting so I can actively influence the organisation agenda.

## Acceptance Criteria

1. Have a proposals & votings section within an organisation 
2. Create a proposal flow 
2.1 select out of all proposal types (eg: spending, campaign withdrawal, membership application, two-choice, multiple-choice, single select, multi select)
2.2 select voting type (eg. simple majority, voting power, consider quorum () 
3. voting period (start, end)
4. List proposals  
4.1 vote on proposals

## Additional Information

- not all ideas are mandatory for AA cycle, please focus for AA cycle on currently active votings: campaign withdrawal, simple two-choice votings.   
-  bring proposal and types into a meaningful priority order
- outcome should be wireframes and MVP for AA cycle

## Figma Links
Pls have a look at the 
Wireframes for Create & vote on proposal
https://www.figma.com/file/NQ2MpTJlQ1fwWhSZ5hsHCx/Wireframe-%26-Sketches?node-id=295%3A31999
@5-mark

**Comment by DarkNebula0** [comment]
UX: Already implemented.
Voting is planned for the current sprint. #118
