### ISSUE TITLE
Deploy Subsquid

### ISSUE THREAD

**Issue by Persqual** [gamedaoco/gamedao-haiku#97]
## User Story
As frontend developer I want to query all chain information through a graphql api so I can use information into the frontend easily, gain performance and separate frontend from backend. The GraphQL endpoint should be deployed in the GameDAO infrastructure. (GameDAO-GitHub-Account instead of a Private-GitHub-Account)

## Acceptance Criteria

1. GraphQL via endpoint reachable
2. GraphQL exposes chain data

## Additional Information

Deployment:
1. Go to https://app.subsquid.io/sign-in 
2. Login via GitHub 
3. Go to https://app.subsquid.io/dashboard
4. Create a new Squid
5. Checkout the [gamedao-protocol-indexer](https://github.com/gamedaoco/gamedao-graph) repo
6. Run yarn / npm install
7. Go back to the Squid Website and run the commands on the right side (sqd auth & sqd release)

npx sqd auth --key sqd_key
npx sqd squid:release squid_name@version --source https://github.com/gamedaoco/gamedao-graph#master
Example:
npx sqd squid:release gamedao-protocol-indxer@v001 --source https://github.com/gamedaoco/gamedao-graph#master

## How to test

1. Go to the GraphQL endpoint
2. Check different chain data against the chain directly on polkadot.js app

**Comment by DarkNebula0** [comment]
Outdated
